### ISSUE TITLE
Linux Installation

### ISSUE THREAD

**Issue by jessequinn** [kbsezginel/nanocar-avogadro#5]
I followed the instructions for installing the nanocar for avogadro2 linux version. However, the workflow directory that is installed in /home/user/.local/share/OpenChemistry/Avogadro/workflows does not generate a nanocar option under build after restarting the app. Should this plugin be placed in commands or some other directory?

**Comment by kbsezginel** [comment]
There was a discussion in the 2018 Avogadro user group meeting by @ghutchis about renaming the `workflows` directory to `commands`. I haven't build Avogadro 2 in some time so that change might have gone through. If there is a `commands` folder under `/home/user/.local/share/OpenChemistry/Avogadro` try installing to that location. You can modify the installer script in line 22:
```
workflows_dir = os.path.join(AVOGADRO_PLUGIN_DIR, 'workflows')
```
and change `workflows` to `commands` to copy all the files.

Let me know if that works, if not I can rebuild Avogadro and try to find a solution.

**Comment by jessequinn** [comment]
So this is where I am at. 

After installing several dependencies for python, specifically your version of angstrom as I believe pip finds and installs ```0.0.4```, and moving from workflows to commands folder, i am down to a single error

```bash
ScriptLoader::queryProgramName: Unable to retrieve program name for "/home/jessequinn/.local/share/OpenChemistry/Avogadro/commands/uff_nonbonded.csv" ; "Error running script '/home/jessequinn/.pyenv/shims/python /home/jessequinn/.local/share/OpenChemistry/Avogadro/commands/uff_nonbonded.csv --display-name --lang en_US': Abnormal exit status 1 (Unknown error.: Unknown error)\n\nOutput:\n  File \"/home/jessequinn/.local/share/OpenChemistry/Avogadro/commands/uff_nonbonded.csv\", line 1\n    Element,distance xi (Å),energy Di kcal/mol\n                      ^\nSyntaxError: invalid syntax\n"
```
and the following shows in the Build menu now

Nanocar - add chasis
               - connect wheel
               - LAMMPS Setup
               - Metal Surface

**Comment by kbsezginel** [comment]
The `angstrom` package in pip is not my package so you would need to install mine from here: https://github.com/kbsezginel/angstrom.git.

That csv error is fine, it's basically trying to parse all the files in that directory and throws a warning since it's not a Python file.

If you install my `angstrom` package everything should work.

Did you end up copying everything to `commands` directory?

**Comment by jessequinn** [comment]
As stated previously, all is well from what i can tell after doing what i stated above. However, i would highly suggest and the same to the creator of avogadro2, that you guys supply a Requirements.txt so installers of your scripts can get up and running quickly. Pip freeze > Requirements.txt.. so we can simply pip install -r Requiments.txt. 

Thanks for the help.

Regards,

**Comment by kbsezginel** [comment]
My bad, I should have read more carefully. I am glad it all worked fine, I will be updating `requirements.txt` shortly.

**Comment by ghutchis** [comment]
at the moment, creating a `venv` and processing `requirements.txt` is on the drawing board for Avogadro's downloader code, but is still an open issue:
https://github.com/OpenChemistry/avogadrolibs/issues/234
